labels:
  - HR
  - 生成AI
  - 機械学習
  - 深層学習
  - 自然言語処理
  - コンピュータビジョン
  - 推薦システム
  - 検索
  - 因果推論・統計
  - A/Bテスト
  - 特徴量エンジニアリング
  - データ品質
  - MLOps
  - データエンジニアリング
  - データサイエンス
  - インフラ
  - 論文紹介
  - 日本国内
  - 海外
